name: continuous-integration
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: curl, intl, mbstring, simplexml
          php-version: 8.3
      - name: Install dependencies
        uses: ramsey/composer-install@v3
      - name: Run tests
        run: composer test
