name: Continuous integration
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        run: |
          php --version
          composer --version
      - name: Fetch sources
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          composer global require cedx/coveralls
          composer install --no-interaction
      - name: Run tests
        run: composer run-script test
      - name: Collect code coverage
        env:
          CI: true
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: success()
        run: composer run-script coverage
