name: main
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          extensions: curl, intl, mbstring, simplexml
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-${{runner.os}}-composer-${{hashFiles('composer.lock')}}
          restore-keys: php-${{runner.os}}-composer-
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: composer test
      - name: Collect code coverage
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: var/coverage.xml
