name: run-tests
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          extensions: curl, intl, mbstring, simplexml
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-${{runner.os}}-composer-${{hashFiles('composer.lock')}}
          restore-keys: php-${{runner.os}}-composer-
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: composer test
